CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "Patients" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "FullName" character varying(255) NOT NULL,
    "DoB" date NOT NULL,
    "Gender" integer NOT NULL,
    "PhoneNo" character varying(20) NOT NULL,
    "Address" character varying(255) NOT NULL,
    "Email" character varying(100),
    "Allergies" character varying(512) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Patients" PRIMARY KEY ("Id")
);

CREATE TABLE "Users" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "FullName" character varying(255) NOT NULL,
    "Email" character varying(100) NOT NULL,
    "Password" character varying(255) NOT NULL,
    "Role" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
);

CREATE TABLE "LabTests" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "TestName" character varying(255) NOT NULL,
    "Description" text,
    "Result" text NOT NULL,
    "Status" integer NOT NULL,
    "PatientId" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_LabTests" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_LabTests_Patients_PatientId" FOREIGN KEY ("PatientId") REFERENCES "Patients" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Doctors" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "PhoneNo" character varying(20) NOT NULL,
    "Specialization" character varying(100) NOT NULL,
    "UserId" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Doctors" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Doctors_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Appointments" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "PatientId" integer NOT NULL,
    "DoctorId" integer NOT NULL,
    "Date" date NOT NULL,
    "Time" time without time zone NOT NULL,
    "Reason" character varying(255),
    "Status" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Appointments" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Appointments_Doctors_DoctorId" FOREIGN KEY ("DoctorId") REFERENCES "Doctors" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Appointments_Patients_PatientId" FOREIGN KEY ("PatientId") REFERENCES "Patients" ("Id") ON DELETE CASCADE
);

CREATE TABLE "DoctorSchedules" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Day" integer NOT NULL,
    "StartTime" time without time zone NOT NULL,
    "EndTime" time without time zone NOT NULL,
    "DoctorId" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_DoctorSchedules" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_DoctorSchedules_Doctors_DoctorId" FOREIGN KEY ("DoctorId") REFERENCES "Doctors" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Diagnoses" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "PatientId" integer NOT NULL,
    "Diagnosis" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Diagnoses" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Diagnoses_Patients_PatientId" FOREIGN KEY ("PatientId") REFERENCES "Patients" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Prescriptions" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "PatientId" integer NOT NULL,
    "MedicationName" character varying(255) NOT NULL,
    "Dosage" character varying(50) NOT NULL,
    "Frequency" character varying(50) NOT NULL,
    "Duration" character varying(50) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Prescriptions" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Prescriptions_Patients_PatientId" FOREIGN KEY ("PatientId") REFERENCES "Patients" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_Appointments_DoctorId" ON "Appointments" ("DoctorId");

CREATE INDEX "IX_Appointments_PatientId" ON "Appointments" ("PatientId");

CREATE INDEX "IX_Diagnoses_PatientId" ON "Diagnoses" ("PatientId");

CREATE INDEX "Doctor_PhoneNo_Index" ON "Doctors" ("PhoneNo");

CREATE INDEX "IX_Doctors_UserId" ON "Doctors" ("UserId");

CREATE INDEX "IX_DoctorSchedules_DoctorId" ON "DoctorSchedules" ("DoctorId");

CREATE INDEX "IX_LabTests_PatientId" ON "LabTests" ("PatientId");

CREATE UNIQUE INDEX "Patient_PhoneNo_Index" ON "Patients" ("PhoneNo");

CREATE INDEX "IX_Prescriptions_PatientId" ON "Prescriptions" ("PatientId");

CREATE INDEX "User_Email_Index" ON "Users" ("Email");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20241213070637_Initial', '9.0.0');

CREATE TABLE "Billings" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Date" date NOT NULL,
    "SubTotal" numeric NOT NULL,
    "Tax" numeric NOT NULL,
    "Total" numeric NOT NULL,
    "PaidAmount" numeric NOT NULL,
    "RemainingBalance" numeric NOT NULL,
    "Status" integer NOT NULL,
    "PatientId" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Billings" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Billings_Patients_PatientId" FOREIGN KEY ("PatientId") REFERENCES "Patients" ("Id") ON DELETE CASCADE
);

CREATE TABLE "BillItems" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Description" text NOT NULL,
    "Quantity" integer NOT NULL,
    "UnitPrice" numeric NOT NULL,
    "Total" numeric NOT NULL,
    "BillingId" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_BillItems" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_BillItems_Billings_BillingId" FOREIGN KEY ("BillingId") REFERENCES "Billings" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Payments" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Amount" numeric NOT NULL,
    "Date" date NOT NULL,
    "BillingId" integer NOT NULL,
    "TransactionId" character varying(100),
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Payments" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Payments_Billings_BillingId" FOREIGN KEY ("BillingId") REFERENCES "Billings" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_Billings_PatientId" ON "Billings" ("PatientId");

CREATE INDEX "IX_BillItems_BillingId" ON "BillItems" ("BillingId");

CREATE INDEX "IX_Payments_BillingId" ON "Payments" ("BillingId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20241213074917_BillingTables', '9.0.0');

CREATE TABLE "Inventories" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(255) NOT NULL,
    "Quantity" integer NOT NULL,
    "MinQuantity" integer NOT NULL,
    "ExpirationDate" date NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Inventories" PRIMARY KEY ("Id")
);

CREATE TABLE "Suppliers" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(255) NOT NULL,
    "ContactInfo" character varying(255) NOT NULL,
    "Address" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Suppliers" PRIMARY KEY ("Id")
);

CREATE TABLE "InventoryLogs" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "SupplierId" integer,
    "InventoryId" integer NOT NULL,
    "Quantity" integer NOT NULL,
    "Description" text NOT NULL,
    "Type" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_InventoryLogs" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_InventoryLogs_Inventories_InventoryId" FOREIGN KEY ("InventoryId") REFERENCES "Inventories" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_InventoryLogs_Suppliers_SupplierId" FOREIGN KEY ("SupplierId") REFERENCES "Suppliers" ("Id")
);

CREATE INDEX "IX_InventoryLogs_InventoryId" ON "InventoryLogs" ("InventoryId");

CREATE INDEX "IX_InventoryLogs_SupplierId" ON "InventoryLogs" ("SupplierId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20241214075929_AddNewTables', '9.0.0');

ALTER TABLE "Prescriptions" ADD "AppointmentId" integer NOT NULL DEFAULT 0;

ALTER TABLE "LabTests" ADD "AppointmentId" integer NOT NULL DEFAULT 0;

ALTER TABLE "Diagnoses" ADD "AppointmentId" integer NOT NULL DEFAULT 0;

CREATE INDEX "IX_Diagnoses_AppointmentId" ON "Diagnoses" ("AppointmentId");

CREATE INDEX "IX_Prescriptions_AppointmentId" ON "Prescriptions" ("AppointmentId");

CREATE INDEX "IX_LabTests_AppointmentId" ON "LabTests" ("AppointmentId");

ALTER TABLE "Diagnoses" ADD CONSTRAINT "FK_Diagnoses_Appointments_AppointmentId" FOREIGN KEY ("AppointmentId") REFERENCES "Appointments" ("Id") ON DELETE CASCADE;

ALTER TABLE "LabTests" ADD CONSTRAINT "FK_LabTests_Appointments_AppointmentId" FOREIGN KEY ("AppointmentId") REFERENCES "Appointments" ("Id") ON DELETE CASCADE;

ALTER TABLE "Prescriptions" ADD CONSTRAINT "FK_Prescriptions_Appointments_AppointmentId" FOREIGN KEY ("AppointmentId") REFERENCES "Appointments" ("Id") ON DELETE CASCADE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20241214094324_RelationWithAppointments', '9.0.0');

ALTER TABLE "Billings" ADD "AppointmentId" integer NOT NULL DEFAULT 0;

CREATE INDEX "IX_Billings_AppointmentId" ON "Billings" ("AppointmentId");

ALTER TABLE "Billings" ADD CONSTRAINT "FK_Billings_Appointments_AppointmentId" FOREIGN KEY ("AppointmentId") REFERENCES "Appointments" ("Id") ON DELETE CASCADE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20241215082024_UpdateBillingTable', '9.0.0');

ALTER TABLE "Appointments" DROP COLUMN "Reason";

ALTER TABLE "Appointments" ADD "AppointmentTypeId" integer;

CREATE TABLE "AppointmentTypes" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Fees" numeric NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_AppointmentTypes" PRIMARY KEY ("Id")
);

CREATE INDEX "IX_Appointments_AppointmentTypeId" ON "Appointments" ("AppointmentTypeId");

ALTER TABLE "Appointments" ADD CONSTRAINT "FK_Appointments_AppointmentTypes_AppointmentTypeId" FOREIGN KEY ("AppointmentTypeId") REFERENCES "AppointmentTypes" ("Id");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250111083553_AddAppointmentTypeTable', '9.0.0');

ALTER TABLE "LabTests" ADD "Fees" numeric NOT NULL DEFAULT 0.0;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250111111113_UpdateLabTestTable', '9.0.0');

COMMIT;

